export const API_DATA_HAS_ERRORED = 'API_DATA_HAS_ERRORED';
export const API_DATA_IS_LOADING = 'API_DATA_IS_LOADING';

export const SET_QUIZ_STATUS = 'SET_QUIZ_STATUS';
export const SAVE_ANSWER = 'SAVE_ANSWER';
export const SET_CURRENT_QUESTION_NUMBER = 'SET_CURRENT_QUESTION_NUMBER';
export const SET_HEADING = 'SET_HEADING';
export const SET_QUIZ_DATA = 'SET_QUIZ_DATA';